apiVersion: v1
kind: PersistentVolume
metadata:
  name: rating-postgres-pv
  namespace: zuidui
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard 
  hostPath:
    path: "/mnt/data/postgres"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rating-postgres-pvc
  namespace: zuidui
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2