apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: zuidui/user-service-dev:0.0.1-rc07
        ports:
        - containerPort: 8082
        env:
        - name: APP_MODULE
          value: "main:app"
        - name: APP_PORT
          value: "8082"
        - name: APP_HOST
          value: "0.0.0.0"
        - name: APP_DESCRIPTION
          value: "User service for MCA project"
        - name: API_PREFIX
          value: "/api/v1"
        - name: API_GATEWAY_HOST
          value: "api-gateway"
        - name: API_GATEWAY_PORT
          value: "8081"
        - name: BROKER_HOST
          value: "events-store"
        - name: BROKER_PORT
          value: "5672"
        - name: QUEUE_NAME
          value: "user-events"
        - name: PYTHONPATH
          value: "/app/src"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
