apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-bbdd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-bbdd
  template:
    metadata:
      labels:
        app: user-bbdd
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "admin"
        - name: POSTGRES_DB
          value: "mydatabase"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-bbdd-service
spec:
  selector:
    app: user-bbdd
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
