apiVersion: v1
kind: PersistentVolume
metadata:
  name: teams-postgres-pv
  namespace: zuidui
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teams-postgres-pvc
  namespace: zuidui
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ebs-sc