apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
  namespace: zuidui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
        - name: cache
          image: redis:latest
          ports:
            - containerPort: 6379           

---
apiVersion: v1
kind: Service
metadata:
  name: cache
  namespace: zuidui
spec:
  selector:
    app: cache
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
