apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-store-queue
  namespace: zuidui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-store-queue
  template:
    metadata:
      labels:
        app: events-store-queue
    spec:
      containers:
        - name: events-store-queue
          image: rabbitmq:3-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              value: "guest"
          ports:
            - containerPort: 5672
            - containerPort: 15672
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "256Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: events-store-queue
  namespace: zuidui
spec:
  type: ClusterIP
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
  selector:
    app: events-store-queue
