apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: zuidui
data:
  APP_PORT: "8080"
  APP_DESCRIPTION:  "Frontend for the MCA TFM"
  API_GATEWAY_HOST:  a9818d7ad55d04c29b497ce52418be8d-688892677.us-east-1.elb.amazonaws.com #loadbalancer ip
  API_GATEWAY_PORT: "8081"
  HOST_NAME: a9818d7ad55d04c29b497ce52418be8d-688892677.us-east-1.elb.amazonaws.com #loadbalancer ip 
