apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.teamService.volumes.pvName }}
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.teamService.volumes.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.teamService.volumes.hostPath }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:s
  name: {{ .Values.teamService.volumes.pvcName }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.teamService.volumes.storage }}
  storageClassName: {{ .Values.teamService.volumes.storageClassName }} 