apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apiGateway.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.apiGateway.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.apiGateway.name }}
    spec:
      containers:
        - name: {{ .Values.apiGateway.name }}
          image: "{{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag }}"
          env:
            {{- toYaml .Values.apiGateway.envVars | nindent 12 }}
          ports:
            - containerPort: {{ .Values.apiGateway.containerPort }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiGateway.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.apiGateway.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.apiGateway.service.port }}
      targetPort: {{ .Values.apiGateway.service.port }}
  type: {{ .Values.apiGateway.service.type }}
