apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }} #tfm-local
    http: 
      paths:
      - path: /(.*)
        pathType: {{ .Values.ingress.pathType }}
        backend:
          service:
            name: frontend
            port:
              number: {{ .Values.ingress.portFrontend }}
      - path: /api/(.*)
        pathType: {{ .Values.ingress.pathType }}
        backend:
          service:
            name: api-gateway
            port:
              number: {{ .Values.ingress.portApiGateway }}
      - path: /api/v1/(.*)
        pathType: {{ .Values.ingress.pathType }}
        backend:
          service:
            name: api-gateway
            port:
              number: {{ .Values.ingress.portApiGateway }}


    
