apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: zuidui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: zuidui/api-gateway-dev:latest
          env:
            - name: APP_PORT
              value: "8081"
            - name: APP_HOST
              value: "0.0.0.0"
            - name: APP_MODULE
              value: "main:app"
            - name: PYTHONPATH
              value: "/app/src"
            - name: DEBUG_PORT
              value: "5678"
            - name: TEAM_SERVICE_HOST
              value: "team-service"
            - name: TEAM_SERVICE_PORT
              value: "8082"  
            - name: FRONTEND_SERVICE_HOST
              value: "frontend"
            - name: FRONTEND_SERVICE_PORT
              value: "8080"
            - name: RATING_SERVICE_HOST
              value: "rating-service"
            - name: RATING_SERVICE_PORT
              value: "8083"
            - name: BROKER_HOST
              value: "events-store"
            - name: BROKER_PORT
              value: "5672"
            - name: BROKER_HEARTBEAT
              value: "60"
            - name: BROKER_CONNECTION_ATTEMPTS
              value: "5"
            - name: BROKER_CONNECTION_TIMEOUT
              value: "300"
            - name: BROKER_ATTEMPT_DELAY
              value: "5"
            - name: QUEUE_NAME
              value: "events-queue"
            - name: EXCHANGE_NAME
              value: "events-exchange"
          ports:
            - containerPort: 8081
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
        

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: zuidui
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
