apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: zuidui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: zuidui/frontend-dev:latest
          env:
            - name: APP_PORT
              value: "8080"
            - name: API_GATEWAY_PORT
              value: "8081"                
            - name: API_GATEWAY_HOST
              value: "tfm-local"      
          ports:
            - containerPort: 80              
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: zuidui
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: frontend
