
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: zuidui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "admin@admin.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "admin"
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi

---

apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: zuidui
spec:
  type: NodePort  # accedo con ip cluter: puerto del pod
  ports:
    - name: http
      port: 5051
      targetPort: 80
      nodePort: 30001
  selector:
    app: pgadmin
